Casting List as an array using NumPy

In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Creating Array using NumPy

In [78]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [84]:
np.arange(4)

array([0, 1, 2, 3])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [90]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [94]:
np.linspace(2.0,3.0,5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [99]:
np.eye(2)   #Identity Matrix


array([[1., 0.],
       [0., 1.]])

In [102]:
np.random.rand()

0.4525772076060275

In [43]:
np.random.rand(5)

array([0.42679237, 0.42011371, 0.33249411, 0.66659425, 0.48497099])

In [103]:
(np.random.rand(5,2)*10)

array([[0.88031013, 8.54313827],
       [4.24635006, 9.50604447],
       [9.74892037, 2.2050548 ],
       [8.98733869, 5.00693213],
       [3.58180263, 0.51940721]])

In [45]:
np.random.randn(2,5)

array([[-0.490421  , -0.15042695,  1.81142787, -1.74651519, -0.28382751],
       [ 1.84832501,  0.93383933,  0.53808096, -0.70720228, -2.87746682]])

In [104]:
np.random.randint(5,20,10)

array([17, 13,  8, 19, 15,  5, 19,  5, 17, 10])

In [105]:
np.random.randint(5,20,(2,2))

array([[19, 17],
       [13, 15]])

Attributes of an array

In [59]:
arr = np.arange(25)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [61]:
ranarr = np.random.randint(0,50,10)

In [62]:
ranarr

array([ 2, 19, 25, 21, 19, 47, 25, 34,  7, 10])

In [65]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
ranarr

array([ 2, 19, 25, 21, 19, 47, 25, 34,  7, 10])

In [67]:
ranarr.min()

2

In [68]:
ranarr.max()

47

In [70]:
ranarr

array([ 2, 19, 25, 21, 19, 47, 25, 34,  7, 10])

In [69]:
ranarr.argmax()     #Location of max value

5

In [71]:
ranarr.argmin()     #Location of min Value 

0

In [72]:
arr.shape

(25,)

In [74]:
arr = arr.reshape(5,5)

In [75]:
arr.shape

(5, 5)

In [76]:
arr.dtype

dtype('int32')