NumPy Indexing and Selection for 1-D Array

In [96]:
import numpy as np

In [97]:
arr = np.arange(0,11)

In [98]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr[8]

8

In [100]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [101]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [102]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [103]:
arr[0:5] = 100

In [104]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [105]:
arr = np.arange(0,11)

In [106]:
slice_of_arr = arr[0:6]

In [107]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [108]:
slice_of_arr[:] = 99

In [109]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [110]:
arr  #slice of array is just a view of arr and not the copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [111]:
arr_copy = arr.copy()

In [112]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [113]:
arr_copy[:] = 100

In [114]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [115]:
arr  #Unaffected as we copied this time

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

NumPy Indexing and Selection for 2-D Array

In [116]:
arr_2d = np.array([[1,2,3],[5,10,15],[45,34,23]])

In [117]:
arr_2d

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [45, 34, 23]])

In [118]:
arr_2d[1]

array([ 5, 10, 15])

In [119]:
arr_2d[1][0]

5

In [120]:
arr_2d[2,1]

34

In [121]:
arr_2d

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [45, 34, 23]])

In [122]:
arr_2d[1:,:2]

array([[ 5, 10],
       [45, 34]])

In [123]:
arr_2d[:2,1:]

array([[ 2,  3],
       [10, 15]])

In [124]:
arr_2d[:2]

array([[ 1,  2,  3],
       [ 5, 10, 15]])

In [125]:
arr_2d[1:]

array([[ 5, 10, 15],
       [45, 34, 23]])

Conditional Selection

In [126]:
arr = np.arange(1,11)

In [127]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
bool_arr = arr > 5

In [129]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [130]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [131]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [132]:
arr[arr < 3]

array([1, 2])

In [133]:
arr_2d = np.arange(50).reshape(5,10)

In [134]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [135]:
arr_2d[1:3,2:5]

array([[12, 13, 14],
       [22, 23, 24]])

In [136]:
arr_2d[1:,5:7]

array([[15, 16],
       [25, 26],
       [35, 36],
       [45, 46]])